Rename getters to be more inline with Golang idioms
open-feature/golang-sdk pull request #23
Opened 2022-07-23 11:45 UTC by sonarypt

### Why

Rename getters to be more inline with Golang idioms. Close #22

### What changed

16 functions were edited in these files. `GetClient()` is the only function that cannot be edited, else it will conflict with `Client` struct in the code.

2022-07-23 15:04 UTC, Akshit42-hue requested changes
Hey @sonarypt. Please sign-off your commit 
ref:- [DCO](https://docs.pi-hole.net/guides/github/how-to-signoff/)

2022-07-25 14:47 UTC, toddbaert commented
I'm not against this, but `GetBooleanValue` etc, aren't REALLY getters (a simple parameter-less method backed by a corresponding field). I'm not 100% convinced this is actually more idiomatic as a method name, but I'm also not a golang expert. @skyerus @james-milligan what are your thoughts? See #22 for more details.

2022-07-25 15:22 UTC, james-milligan commented
I think that regardless of these methods being getters or not (I don't believe they are) that these changes technically are more idiomatic - its my understanding that when it comes to naming conventions for functions shorter = better and the addition of ```Get``` to each function does not add a lot of value in terms of readability.  
In my opinion, the function signature: 
```BooleanValue(flag string, defaultValue bool, evalCtx EvaluationContext, options ...EvaluationOption) (bool, error)```
is no less readable than:
```GetBooleanValue(flag string, defaultValue bool, evalCtx EvaluationContext, options ...EvaluationOption) (bool, error)```
so my vote is 👍

2022-07-25 19:56 UTC, toddbaert commented
@james-milligan you've convinced me!

2022-07-27 13:18 UTC, beeme1mr commented
Hi @sonarypt, could you please sign-off your commits? This is a requirement from the CNCF. Thanks for your contribution.

2022-07-28 16:36 UTC, beeme1mr commented
Hey @sonarypt, we're working on our documentation and would like to get this change in place.

https://github.com/open-feature/docs.openfeature.dev/pull/31

FYI, @skyerus

2022-07-29 13:13 UTC, skyerus commented
Recreated these changes with a signed commit: https://github.com/open-feature/golang-sdk/pull/29

2022-07-29 13:41 UTC, beeme1mr commented
Closing because the DCO sign-off hasn't happened.

2022-07-29 13:41 UTC, closed without merging